#!/bin/bash -ue

#-------------------------------------------------------------------------------
# Copyright (C) 2021, HENSOLDT Cyber GmbH
#
# Set common paths for the analysis project.
#-------------------------------------------------------------------------------

unset_common_paths () {
    unset AXIVION_DIR
    unset DEMO_DIR
    unset SOURCE_DIR
    unset SANDBOX_DIR
    unset BUILD_DIR
}

# set axivion directory
AXIVION_DIR="$(cd "$(dirname "$0")" >/dev/null 2>&1 && pwd)"

# set derived directories
DEMO_DIR="${AXIVION_DIR}/.."                # e.g. /host/demo_hello_world
SOURCE_DIR=${DEMO_DIR}                      # e.g. /host/demo_hello_world

SANDBOX_DIR=$(cd /host; realpath *sandbox*) # e.g. /host/sandbox
BUILD_DIR="/home/user/build_analysis"       # folder within container
